version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - COLDKEY_SWAP_DISCORD_WEBHOOK_URL=${COLDKEY_SWAP_DISCORD_WEBHOOK_URL}
    command: ["python", "main.py"]